name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 4: Run lint checks
      - name: Run lint
        run: npx nx lint backend

      # Step 5: Build the project
      - name: Build the project
        run: npx nx build backend

      # Step 6: Run tests (if applicable)
      # - name: Run tests
      #   run: npx nx test backend
      #   env:
      #     NODE_ENV: test

      # Optional: Upload build artifacts (e.g., for debugging)
      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
